language: node_js
node_js:
  - "0.10"

branches:
  only:
    - master

install:
  - npm install
  - bower install

# after_script:
#   - npm run coveralls

# notifications:
#   webhooks: http://travalizit.org/builds
